/*
 * crdt_types.h - Custom C CRDT primitives for IRC network state
 *
 * Purpose-built CRDT data structures for IRC's high-churn S2S state,
 * per the CRDT-mesh proposal §17.1. Four primitives:
 *
 *   CrdtTag          - globally-unique OR-Set operation identifier
 *   CrdtORSet        - observed-remove set with PRIORITY removes (KICK > JOIN)
 *   CrdtLWWMap       - last-writer-wins map (HLC-ordered), no tombstones
 *   CrdtStateVector  - per-server highest-seq tracking (sync + causal GC)
 *
 * Design constraints (so the engine is unit-testable in isolation and
 * carries no IRCd coupling):
 *   - libc + crdt_hlc.h ONLY. No feature_int/Client/MyMalloc/sendto_*.
 *   - The integration/sync layer (future crdt_sync.c / m_crdt.c) is what
 *     reads feature flags and touches the wire; these primitives do not.
 *
 * Tombstone reclamation: CrdtORSet supports true causal-stability GC
 * (crdt_orset_gc) — the key advantage over Y-CRDT, which retains tombstone
 * metadata forever (proposal §17.2). LWW-Map needs no tombstones at all.
 */

#ifndef INCLUDED_crdt_types_h
#define INCLUDED_crdt_types_h

#include <stdint.h>
#include <stddef.h>
#include "crdt_hlc.h"

/** P10 numeric space — max servers on a network (== NN_MAX_SERVER).
 *  State vectors are indexed by server numeric. */
#define CRDT_MAX_SERVERS 4096

/* Forward declaration: crdt_orset_gc() takes a state vector, defined below. */
struct CrdtStateVector;

/*
 * ============================================================
 * CrdtTag — unique OR-Set operation identifier
 * ============================================================
 */

/** Globally unique tag for an OR-Set add. Generated by the originating
 *  server; never reused. Ordered lexicographically on (origin, seq). */
struct CrdtTag {
  uint16_t origin;   /**< Server numeric that created the add */
  uint64_t seq;      /**< Per-server monotonic sequence number */
};

/** Compare two tags. Returns -1, 0, 1. */
static inline int crdt_tag_cmp(struct CrdtTag a, struct CrdtTag b)
{
  if (a.origin != b.origin) return a.origin < b.origin ? -1 : 1;
  if (a.seq != b.seq) return a.seq < b.seq ? -1 : 1;
  return 0;
}

/** Equality test for two tags. */
static inline int crdt_tag_eq(struct CrdtTag a, struct CrdtTag b)
{
  return a.origin == b.origin && a.seq == b.seq;
}

/*
 * ============================================================
 * Remove priorities (proposal §17.4.3)
 * ============================================================
 * A priority-0 remove (PART) only suppresses the specific add-tags it
 * targets — a concurrent JOIN (new tag) survives (add-wins). A priority>0
 * remove (KICK / services / ircd) suppresses the element entirely, beating
 * any concurrent add.
 */
#define CRDT_PRIORITY_USER      0   /**< PART — voluntary leave */
#define CRDT_PRIORITY_CHANOP    2   /**< KICK by channel operator */
#define CRDT_PRIORITY_SERVICES  3   /**< KICK by ChanServ/X3 */
#define CRDT_PRIORITY_IRCD      4   /**< server-level forced removal */

/*
 * ============================================================
 * CrdtORSet — observed-remove set with priority removes
 * ============================================================
 */

/** One element of an OR-Set. Holds every concurrent add-tag for the value
 *  (multiple servers may have added it during a partition). */
struct CrdtORSetEntry {
  char                  *key;        /**< Element value (NUL-terminated copy) */
  uint32_t               key_len;
  struct CrdtTag        *add_tags;   /**< Dynamic array of add tags */
  uint16_t               add_count;
  uint16_t               add_cap;
  struct CrdtORSetEntry *ht_next;    /**< Hash-bucket chain */
};

/** A remove record (tombstone), keyed by the add-tag it covers. */
struct CrdtTombstone {
  struct CrdtTag        tag;         /**< The add-tag being removed */
  uint8_t               priority;    /**< CRDT_PRIORITY_* */
  struct CrdtTombstone *ht_next;     /**< Hash-bucket chain */
};

/** Observed-remove set: elements hash table + tombstone hash table. */
struct CrdtORSet {
  struct CrdtORSetEntry **buckets;
  uint32_t                nbuckets;
  uint32_t                entry_count;   /**< total entries (present or not) */
  struct CrdtTombstone  **tomb;
  uint32_t                tomb_nbuckets;
  uint32_t                tomb_count;
};

void crdt_orset_init(struct CrdtORSet *set);
void crdt_orset_clear(struct CrdtORSet *set);   /**< free all storage */

/** Present-test honouring priority removes (proposal §17.4.2):
 *  present iff (>=1 add-tag not covered by any tombstone) AND
 *  (no priority>0 tombstone covers any of the element's add-tags). */
int crdt_orset_contains(const struct CrdtORSet *set,
                        const char *key, uint32_t key_len);

/** Returns 1 iff the entry EXISTS in the set but is no longer contained (all
 *  add-tags tombstoned / priority-removed) — i.e. an explicit remove happened.
 *  Returns 0 if the entry is ABSENT (never added / GC'd). The safe gate for a
 *  doc→live reconcile-remove: removes only the explicitly-tombstoned, never the
 *  merely-absent (sync-lag / not-yet-seen-add guard). */
int crdt_orset_is_explicitly_removed(const struct CrdtORSet *set,
                                     const char *key, uint32_t key_len);

/** Local add: register an add-tag (caller supplies a fresh tag). Idempotent. */
void crdt_orset_add(struct CrdtORSet *set, const char *key, uint32_t key_len,
                    struct CrdtTag tag);

/** Local remove: tombstone all current (uncovered) add-tags of key with the
 *  given priority. Writes the tombstoned tags into out_tags[] (up to max_out)
 *  so the caller can record remove ops in the oplog. Returns count tombstoned. */
int crdt_orset_remove(struct CrdtORSet *set, const char *key, uint32_t key_len,
                      uint8_t priority, struct CrdtTag *out_tags, int max_out);

/** Merge a remote add (idempotent). */
void crdt_orset_merge_add(struct CrdtORSet *set, const char *key,
                          uint32_t key_len, struct CrdtTag tag);

/** Merge a remote remove (idempotent): tombstone the given add-tag. */
void crdt_orset_merge_remove(struct CrdtORSet *set, struct CrdtTag tag,
                             uint8_t priority);

/** Causal-stability GC (proposal §17.2): free every tombstone whose
 *  tag.seq <= stable.seq[tag.origin], drop add-tags covered by a stable
 *  tombstone, and free entries left with no add-tags. Returns tombstones freed.
 *
 *  NOTE: only sound over priority-0 (standard OR-Set) churn. Priority>0
 *  removes interact subtly with GC (a late concurrent add can resurrect once
 *  the suppressing tombstones are freed); that is a documented Phase-0
 *  follow-up — do not GC sets that carry live priority>0 removes. */
int crdt_orset_gc(struct CrdtORSet *set, const struct CrdtStateVector *stable);

/** Number of currently-present elements. */
uint32_t crdt_orset_size(const struct CrdtORSet *set);

/** Number of live tombstones (for memory/GC measurement). */
uint32_t crdt_orset_tomb_count(const struct CrdtORSet *set);

typedef void (*crdt_orset_iter_fn)(const char *key, uint32_t key_len,
                                   void *ctx);
/** Visit every PRESENT element. */
void crdt_orset_foreach(const struct CrdtORSet *set,
                        crdt_orset_iter_fn fn, void *ctx);

/*
 * ============================================================
 * CrdtLWWMap — last-writer-wins map (HLC ordered)
 * ============================================================
 * Each key is an independent LWW register. Concurrent writes to the same key
 * resolve by HLC (which already tiebreaks on node_id). Deletes are LWW writes
 * of a tombstone flag — no separate tombstone store, no unbounded growth
 * (proposal §17.1.3): a delete with higher HLC simply wins, and a later write
 * with a still-higher HLC resurrects the key.
 */

struct CrdtLWWValue {
  void       *data;       /**< Value payload (owned copy), NULL if deleted */
  uint32_t    data_len;
  struct HLC  ts;         /**< HLC of the write */
  uint16_t    writer;     /**< Server numeric that wrote it */
};

struct CrdtLWWEntry {
  char                *key;
  uint32_t             key_len;
  struct CrdtLWWValue  val;
  int                  deleted;   /**< 1 if last write was a delete */
  struct CrdtLWWEntry *ht_next;
};

struct CrdtLWWMap {
  struct CrdtLWWEntry **buckets;
  uint32_t              nbuckets;
  uint32_t              entry_count;
};

void crdt_lwwmap_init(struct CrdtLWWMap *map);
void crdt_lwwmap_clear(struct CrdtLWWMap *map);

/** Set key=data if ts beats the existing write (hlc_compare > 0).
 *  Returns 1 if applied, 0 if stale/no-op. Used for both local set and merge. */
int crdt_lwwmap_set(struct CrdtLWWMap *map, const char *key, uint32_t key_len,
                    const void *data, uint32_t data_len,
                    struct HLC ts, uint16_t writer);

/** Get current value (NULL if absent or deleted). */
const struct CrdtLWWValue *crdt_lwwmap_get(const struct CrdtLWWMap *map,
                                           const char *key, uint32_t key_len);

/** Delete key (LWW write of a tombstone). Returns 1 if applied, 0 if stale. */
int crdt_lwwmap_delete(struct CrdtLWWMap *map, const char *key,
                       uint32_t key_len, struct HLC ts, uint16_t writer);

/** Number of live (non-deleted) keys. */
uint32_t crdt_lwwmap_size(const struct CrdtLWWMap *map);

typedef void (*crdt_lwwmap_iter_fn)(const char *key, uint32_t key_len,
                                    const struct CrdtLWWValue *val, void *ctx);
/** Visit every PRESENT (non-deleted) key with its current value. */
void crdt_lwwmap_foreach(const struct CrdtLWWMap *map,
                         crdt_lwwmap_iter_fn fn, void *ctx);

/*
 * ============================================================
 * CrdtStateVector — per-server highest-seq tracking
 * ============================================================
 */

/** sv.seq[numeric] = highest op sequence seen from that server. */
struct CrdtStateVector {
  uint64_t seq[CRDT_MAX_SERVERS];
};

void crdt_sv_init(struct CrdtStateVector *sv);

static inline void crdt_sv_update(struct CrdtStateVector *sv,
                                  uint16_t origin, uint64_t seq)
{
  if (seq > sv->seq[origin]) sv->seq[origin] = seq;
}

static inline int crdt_sv_has_seen(const struct CrdtStateVector *sv,
                                   uint16_t origin, uint64_t seq)
{
  return seq <= sv->seq[origin];
}

/** Component-wise minimum across n state vectors (causal-stability GC). */
void crdt_sv_global_min(struct CrdtStateVector *out,
                        const struct CrdtStateVector *const *vecs, int n);

#endif /* INCLUDED_crdt_types_h */
